{"name": "test_1", "status": "failed", "statusDetails": {"message": "AssertionError: assert 10 == 12", "trace": "def test_1():\n        x = 10\n        y = 12\n>       assert x == y\nE       assert 10 == 12\n\ntest_first.py:5: AssertionError"}, "start": 1647109467207, "stop": 1647109467207, "uuid": "9148e3af-6bd6-4beb-93bb-8fdc5252b791", "historyId": "771ccf05cb6d2b8c99f81ac08355fd3b", "testCaseId": "9c816f376c2bce0c46978efa8898f2cc", "fullName": "test_first#test_1", "labels": [{"name": "suite", "value": "test_first"}, {"name": "host", "value": "DESKTOP-MHJ8SOM"}, {"name": "thread", "value": "13100-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_first"}]}