{"name": "testing_3", "status": "failed", "statusDetails": {"message": "AssertionError: assert 20 == 40", "trace": "def testing_3():\n        x = 10\n        y = 10\n        result = x+y\n>       assert result == 40\nE       assert 20 == 40\n\ntest_first.py:18: AssertionError"}, "start": 1647109467368, "stop": 1647109467369, "uuid": "7e12e077-99f1-499b-b2b6-a210e98287a3", "historyId": "b060e5c2525f5a2cb6ffeab204900af7", "testCaseId": "96851c276d67f1f0b787b908ac42f9ca", "fullName": "test_first#testing_3", "labels": [{"name": "suite", "value": "test_first"}, {"name": "host", "value": "DESKTOP-MHJ8SOM"}, {"name": "thread", "value": "13100-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_first"}]}