{"name": "test_1", "status": "failed", "statusDetails": {"message": "AssertionError: assert 10 == 12", "trace": "def test_1():\n        x = 10\n        y = 12\n>       assert x == y\nE       assert 10 == 12\n\nPytestPrograms\\test_first.py:5: AssertionError"}, "start": 1648822692834, "stop": 1648822692834, "uuid": "83fb2e47-1d5a-43c2-9b9d-136dada5b949", "historyId": "c7ec8c2d09c418e351afada79f88f3d5", "testCaseId": "7001f9a4b0a8d8cb904f3516e5661445", "fullName": "PytestPrograms.test_first#test_1", "labels": [{"name": "parentSuite", "value": "PytestPrograms"}, {"name": "suite", "value": "test_first"}, {"name": "host", "value": "DESKTOP-MHJ8SOM"}, {"name": "thread", "value": "2572-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "PytestPrograms.test_first"}]}