{"name": "testing_3", "status": "failed", "statusDetails": {"message": "AssertionError: assert 20 == 40", "trace": "def testing_3():\n        x = 10\n        y = 10\n        result = x+y\n>       assert result == 40\nE       assert 20 == 40\n\nPytestPrograms\\test_first.py:18: AssertionError"}, "start": 1648822692858, "stop": 1648822692859, "uuid": "c0c88383-f6a3-41b6-a694-9418b1ded4ce", "historyId": "2d1a98a4f97532f1b0c7a29fd3e8c340", "testCaseId": "77d42a300e72f29888e0c40130df534c", "fullName": "PytestPrograms.test_first#testing_3", "labels": [{"name": "parentSuite", "value": "PytestPrograms"}, {"name": "suite", "value": "test_first"}, {"name": "host", "value": "DESKTOP-MHJ8SOM"}, {"name": "thread", "value": "2572-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "PytestPrograms.test_first"}]}