{"name": "test_second", "status": "failed", "statusDetails": {"message": "AssertionError: assert 77 == 88", "trace": "def test_second():\n        a = 33\n        b = 44\n        result = a + b\n>       assert result == 88\nE       assert 77 == 88\n\nPytestPrograms\\test_pythonMarkers.py:18: AssertionError"}, "start": 1648822692920, "stop": 1648822692921, "uuid": "b7a18197-a8b2-4fc5-9248-80e205543d5c", "historyId": "12f51ad72ba0d25ea6230e2ecbfc4215", "testCaseId": "9d79deacba24309fe72844a90b996b35", "fullName": "PytestPrograms.test_pythonMarkers#test_second", "labels": [{"name": "parentSuite", "value": "PytestPrograms"}, {"name": "suite", "value": "test_pythonMarkers"}, {"name": "host", "value": "DESKTOP-MHJ8SOM"}, {"name": "thread", "value": "2572-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "PytestPrograms.test_pythonMarkers"}]}